package reverse;
// Generated 28 Nov 2022, 09:40:25 by Hibernate Tools 6.1.3.Final

import java.sql.Date;

/**
 * ListaempleadosId generated by hbm2java
 */
public class ListaempleadosId implements java.io.Serializable {

	private String apenom;
	private String departamento;
	private Date fecha;
	private String matricula;
	private Double totgastos;
	private Double totventas;

	public ListaempleadosId() {
	}

	public ListaempleadosId(String apenom, String departamento, Date fecha, String matricula, Double totgastos,
			Double totventas) {
		this.apenom = apenom;
		this.departamento = departamento;
		this.fecha = fecha;
		this.matricula = matricula;
		this.totgastos = totgastos;
		this.totventas = totventas;
	}

	public String getApenom() {
		return this.apenom;
	}

	public void setApenom(String apenom) {
		this.apenom = apenom;
	}

	public String getDepartamento() {
		return this.departamento;
	}

	public void setDepartamento(String departamento) {
		this.departamento = departamento;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public String getMatricula() {
		return this.matricula;
	}

	public void setMatricula(String matricula) {
		this.matricula = matricula;
	}

	public Double getTotgastos() {
		return this.totgastos;
	}

	public void setTotgastos(Double totgastos) {
		this.totgastos = totgastos;
	}

	public Double getTotventas() {
		return this.totventas;
	}

	public void setTotventas(Double totventas) {
		this.totventas = totventas;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ListaempleadosId))
			return false;
		ListaempleadosId castOther = (ListaempleadosId) other;

		return ((this.getApenom() == castOther.getApenom()) || (this.getApenom() != null
				&& castOther.getApenom() != null && this.getApenom().equals(castOther.getApenom())))
				&& ((this.getDepartamento() == castOther.getDepartamento())
						|| (this.getDepartamento() != null && castOther.getDepartamento() != null
								&& this.getDepartamento().equals(castOther.getDepartamento())))
				&& ((this.getFecha() == castOther.getFecha()) || (this.getFecha() != null
						&& castOther.getFecha() != null && this.getFecha().equals(castOther.getFecha())))
				&& ((this.getMatricula() == castOther.getMatricula()) || (this.getMatricula() != null
						&& castOther.getMatricula() != null && this.getMatricula().equals(castOther.getMatricula())))
				&& ((this.getTotgastos() == castOther.getTotgastos()) || (this.getTotgastos() != null
						&& castOther.getTotgastos() != null && this.getTotgastos().equals(castOther.getTotgastos())))
				&& ((this.getTotventas() == castOther.getTotventas()) || (this.getTotventas() != null
						&& castOther.getTotventas() != null && this.getTotventas().equals(castOther.getTotventas())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getApenom() == null ? 0 : this.getApenom().hashCode());
		result = 37 * result + (getDepartamento() == null ? 0 : this.getDepartamento().hashCode());
		result = 37 * result + (getFecha() == null ? 0 : this.getFecha().hashCode());
		result = 37 * result + (getMatricula() == null ? 0 : this.getMatricula().hashCode());
		result = 37 * result + (getTotgastos() == null ? 0 : this.getTotgastos().hashCode());
		result = 37 * result + (getTotventas() == null ? 0 : this.getTotventas().hashCode());
		return result;
	}

}
